config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#home'

  get 'static_pages/home'

  get('/holdings/new', { :controller => 'holdings', :action => 'new' })
  get('/create_holding', { :controller => 'holdings', :action => 'create' })

  get('/holdings', { :controller => 'holdings', :action => 'index' })
  get('/holdings/:id', { :controller => 'holdings', :action => 'show' })

  get('/holdings/:id/edit', { :controller => 'holdings', :action => 'edit' })
  get('/update_holding/:id', { :controller => 'holdings', :action => 'update' })

  get('/delete_holding/:id', { :controller => 'holdings', :action => 'destroy' })

  get('/prices/new', { :controller => 'prices', :action => 'new' })
  get('/create_price', { :controller => 'prices', :action => 'create' })

  get('/prices', { :controller => 'prices', :action => 'index' })
  get('/prices/:id', { :controller => 'prices', :action => 'show' })

  get('/prices/:id/edit', { :controller => 'prices', :action => 'edit' })
  get('/update_price/:id', { :controller => 'prices', :action => 'update' })

  get('/delete_price/:id', { :controller => 'prices', :action => 'destroy' })

  get('/etfs/new', { :controller => 'etfs', :action => 'new' })
  post('/etfs', { :controller => 'etfs', :action => 'create' })

  get('/etfs', { :controller => 'etfs', :action => 'index' })
  get('/etfs/:id', { :controller => 'etfs', :action => 'show' })

  get('/etfs/:id/edit', { :controller => 'etfs', :action => 'edit' })
  patch('/update_etf/:id', { :controller => 'etfs', :action => 'update' })

  get('/delete_etf/:id', { :controller => 'etfs', :action => 'destroy' })

  resources :etfs

  get('/allocations/new', { :controller => 'allocations', :action => 'new' })
  get('/create_allocation', { :controller => 'allocations', :action => 'create' })

  get('/allocations', { :controller => 'allocations', :action => 'index' })
  get('/allocations/:id', { :controller => 'allocations', :action => 'show' })

  get('/allocations/:id/edit', { :controller => 'allocations', :action => 'edit' })
  get('/update_allocation/:id', { :controller => 'allocations', :action => 'update' })

  get('/delete_allocation/:id', { :controller => 'allocations', :action => 'destroy' })

  get('/target_portfolios/new', { :controller => 'target_portfolios', :action => 'new' })
  get('/create_target_portfolio', { :controller => 'target_portfolios', :action => 'create' })

  get('/target_portfolios', { :controller => 'target_portfolios', :action => 'index' })
  get('/target_portfolios/:id', { :controller => 'target_portfolios', :action => 'show' })

  get('/target_portfolios/:id/edit', { :controller => 'target_portfolios', :action => 'edit' })
  get('/update_target_portfolio/:id', { :controller => 'target_portfolios', :action => 'update' })

  get('/delete_target_portfolio/:id', { :controller => 'target_portfolios', :action => 'destroy' })

  get('/objectives/new', { :controller => 'objectives', :action => 'new' })
  get('/create_objective', { :controller => 'objectives', :action => 'create' })

  get('/objectives', { :controller => 'objectives', :action => 'index' })
  get('/objectives/:id', { :controller => 'objectives', :action => 'show' })

  get('/objectives/:id/edit', { :controller => 'objectives', :action => 'edit' })
  get('/update_objective/:id', { :controller => 'objectives', :action => 'update' })

  get('/delete_objective/:id', { :controller => 'objectives', :action => 'destroy' })

  get('/accounts/new', { :controller => 'accounts', :action => 'new' })
  get('/create_account', { :controller => 'accounts', :action => 'create' })

  get('/accounts', { :controller => 'accounts', :action => 'index' })
  get('/accounts/:id', { :controller => 'accounts', :action => 'show' })

  get('/accounts/:id/edit', { :controller => 'accounts', :action => 'edit' })
  get('/update_account/:id', { :controller => 'accounts', :action => 'update' })

  get('/delete_account/:id', { :controller => 'accounts', :action => 'destroy' })

end

app/models/etf.rb
class Etf < ActiveRecord::Base
  has_many :allocations
  has_many :holdings
  has_many :prices

  # validates_presence_of :name <---- alternative syntax
  # validates_presence_of :ticker
  validates :name,        :presence => true
  validates :ticker,      :presence => true
  validates :isin,        :presence => true
  validates :asset_class, :presence => true
  validates :currency,    :presence => true
  validates :manager,     :presence => true
  validates :fee,         :presence => true
end

app/controllers/etfs_controller.rb
class EtfsController < ApplicationController

  before_action :authenticate_admin_user!

  def index
    @etfs = Etf.all
  end

  def show
    @etf = Etf.find(params[:id])
  end

  def new
    @etf = Etf.new
  end

  def create
    @etf = Etf.new(etf_params)
    # @etf.name = params[:name]
    # @etf.ticker = params[:ticker]
    # @etf.isin = params[:isin]
    # @etf.asset_class = params[:asset_class]
    # @etf.currency = params[:currency]
    # @etf.manager = params[:manager]
    # @etf.fee = params[:fee]

    if @etf.save
      redirect_to "/etfs", :notice => "Etf created successfully."
    else
      render 'new'
    end
  end


  def edit
    @etf = Etf.find(params[:id])
  end

  def update
    @etf = Etf.find(params[:id])
    @etf.update(etf_params)
    # @etf.name = params[:name]
    # @etf.ticker = params[:ticker]
    # @etf.isin = params[:isin]
    # @etf.asset_class = params[:asset_class]
    # @etf.currency = params[:currency]
    # @etf.manager = params[:manager]
    # @etf.fee = params[:fee]

    if @etf.save
      redirect_to "/etfs", :notice => "Etf updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @etf = Etf.find(params[:id])

    @etf.destroy

    redirect_to "/etfs", :notice => "Etf deleted."
  end

  def etf_params
    params.required(:etf).permit(:name, :ticker, :isin, :asset_class, :currency, :manager, :fee)
  end
end

app/views/etfs/edit.html.erb
<% if @etf.errors.any? %>
<% @etf.errors.full_messages.each do |message| %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= message %>
</div>
<% end %>
<% end %>

<div class="page-header">
</div>


<div class="row">
  <div class=" col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Edit : &emsp; Exchange Traded Fund</h3>
      </div>
      <div class="panel-body">

        <%= form_for(@etf, html: {class: "form-horizontal"}) do |f| %>

        <!-- Label and input for name -->
        <div class="form-group">
          <%= f.label :name, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: "form-control", placeholder: :name  %>
          </div>
        </div>

        <!-- <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @etf.name %>">
            </div>
          </div>
        -->
        <div class="form-group">
          <%= f.label :ticker, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :ticker, class: "form-control", placeholder: :ticker  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :isin, "ISIN", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :isin, class: "form-control", placeholder: :isin  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :asset_class, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :asset_class, class: "form-control", placeholder: :asset_class  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :currency, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :currency, class: "form-control", placeholder: :currency  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :manager, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :manager, class: "form-control", placeholder: :manager  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :fee, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :fee, class: "form-control", placeholder: :fee  %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12">
            <%= f.submit "Update ETF", class: "col-sm-offset-2 col-sm-3 btn btn-primary" %>
            <%= link_to "Cancel", etfs_path, class: " col-sm-offset-1 col-sm-3 btn btn-info" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/etfs/index.html.erb
<div class="page-header">
  <h1>Exchange Traded Funds</h1>
</div>

<p><a href="/etfs/new" class="btn btn-primary">Add a New ETF</a></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticker</th>
      <th>Isin</th>
      <th>Asset class</th>
      <th>Currency</th>
      <th>Manager</th>
      <th>Fee</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @etfs.each do |etf| %>
      <tr>
        <td><%= etf.name %></td>
        <td><%= etf.ticker %></td>
        <td><%= etf.isin %></td>
        <td><%= etf.asset_class %></td>
        <td><%= etf.currency %></td>
        <td><%= etf.manager %></td>
        <td><%= etf.fee %></td>
        <td>
          <a href="/etfs/<%= etf.id %>" class="btn btn-xs btn-primary">
            <i class="fa fa-search-plus"></i>
          </a>
        </td>
        <td>
          <a href="/etfs/<%= etf.id %>/edit" class="btn btn-xs btn-warning">
            <i class="fa fa-edit"></i>
          </a>
        </td>
        <td>
          <a href="/delete_etf/<%= etf.id %>" class="btn btn-xs btn-danger">
            <i class="fa fa-trash-o"></i>
          </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/etfs/new.html.erb
<% if @etf.errors.any? %>
<% @etf.errors.full_messages.each do |message| %>
<div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= message %>
</div>
<% end %>
<% end %>

<div class="page-header">
</div>


<div class="row">
  <div class=" col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Add : &emsp; Exchange Traded Fund</h3>
      </div>
      <div class="panel-body">
        <%= form_for(@etf, html: {class: "form-horizontal"}) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: "form-control", placeholder: :name  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :ticker, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :ticker, class: "form-control", placeholder: :ticker  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :isin, "ISIN", class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :isin, class: "form-control", placeholder: :isin  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :asset_class, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :asset_class, class: "form-control", placeholder: :asset_class  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :currency, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :currency, class: "form-control", placeholder: :currency  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :manager, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :manager, class: "form-control", placeholder: :manager  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :fee, class: "col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :fee, class: "form-control", placeholder: :fee  %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-12">
            <%= f.submit "Create ETF", class: "col-sm-offset-2 col-sm-3 btn btn-primary" %>
            <%= link_to "Cancel", etfs_path, class: " col-sm-offset-1 col-sm-3 btn btn-info" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/etfs/show.html.erb
<div class="page-header">
  <h1>Etf #<%= @etf.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Name</dt>
  <dd><%= @etf.name %></dd>

  <dt>Ticker</dt>
  <dd><%= @etf.ticker %></dd>

  <dt>Isin</dt>
  <dd><%= @etf.isin %></dd>

  <dt>Asset class</dt>
  <dd><%= @etf.asset_class %></dd>

  <dt>Currency</dt>
  <dd><%= @etf.currency %></dd>

  <dt>Manager</dt>
  <dd><%= @etf.manager %></dd>

  <dt>Fee</dt>
  <dd><%= @etf.fee %></dd>

</dl>